Views
Ugboaja-Uchechi/rails-blog-app pull request #5
Opened 2022-02-23 09:12 UTC by Ugboaja-Uchechi

###  Project Requirements

- Implement design from the specified interface.

2022-02-23 10:45 UTC, Emmyn5600 requested changes
Hi @Ugboaja-Uchechi 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet, please work on it and ask for another review.

 ## Required Changes ♻️
 
 - Check the comment under the review.
  
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-02-23 10:45 UTC, Emmyn5600 commented on app/views/user/show.html.erb
> +</div>
- [ ] We need to implement the `comment and likes` features to be displayed in the view using this file.

2022-02-23 10:45 UTC, Emmyn5600 commented on app/views/post/index.html.erb
> +<% end %>
- [ ] Uses `post.recent_comments` to render 5 most recent comments in the `app/views/posts/index.html.erb` page

2022-02-23 22:12 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️

### Hello @Ugboaja-Uchechi  ✋🏼 
#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
___
### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏

![almost](https://media.giphy.com/media/oHwvp6bEuiog0bxg2P/giphy.gif)

___

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_


_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mentioning me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._
___
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-02-23 22:12 UTC, ahmetbozaci commented on app/views/partials/_user.html.erb
> +      <p>Number of posts: <%= user.postsCounter? %></p>
### OPTIONAL
**_It wasn't pointed out earlier. But it is a requirement so ı highly recommend fixing it._**
- [x]  You should fix the post counter.
![image](https://user-images.githubusercontent.com/38635158/155410265-3c9dfd7a-9778-475b-b161-88a5a867b351.png)

2022-02-23 22:12 UTC, ahmetbozaci commented on app/views/partials/_bio.html.erb
> +</div>
### OPTIONAL
**_It wasn't pointed out earlier. But it is a requirement so ı highly recommend fixing it._**
- [x] The bio should come from the user model. You should fix it.

2022-02-23 22:12 UTC, ahmetbozaci commented on app/views/partials/_user.html.erb
> +  </div>
### OPTIONAL
**_It wasn't pointed out earlier. But it is a requirement so ı highly recommend fixing it._**
- [x] The user photo should come from the user model. You should fix it.

2022-02-23 22:12 UTC, ahmetbozaci commented on app/assets/stylesheets/application.css
> +  display: flex;
### OPTIONAL
- [x] For DRY CSS you should combine duplicate properties. 
Example, you can create class `.d-flex { display: flex}` and use this class in HTML file.

- [More information about DRY principles](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/) 

- [Html and css best practices in curriculum](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-02-23 22:12 UTC, ahmetbozaci commented on app/views/partials/_singlepost.html.erb
> +      <p>Post #<%= post.id %> by username <%= post.author %></p>
### OPTIONAL
**_It wasn't pointed out earlier. But it is a requirement so ı highly recommend fixing it._**
- [x] You should fix the post author name. 
![image](https://user-images.githubusercontent.com/38635158/155413357-2ec36a59-abfc-4230-a54f-ad29e0cf59e5.png)

2022-02-23 22:12 UTC, ahmetbozaci commented on app/views/partials/_singlepost.html.erb
> +      <p>Comments: x, Likes: y</p>
### OPTIONAL
**_It wasn't pointed out earlier. But it is a requirement so ı highly recommend fixing it._**
- [x] The comment and like should come from the models. You should fix it.

2022-02-23 22:12 UTC, ahmetbozaci commented on app/views/partials/_comment.html.erb
> +  </div>
### Requirement
- [ ] Nice to add comments on the show page but comments should come from the model. You should fix it.

2022-02-24 11:16 UTC, Ugboaja-Uchechi commented
This is my last review.
I have worked on the required and optional reviews to the best of my knowledge.

2022-02-24 11:44 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Stephanie, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-24 13:44 UTC, merged